openapi: 3.0.3

info:
  title: API для работы с чатами
  version: 1.0.0

tags:
  - name: Chat
    description: Чат

paths:
  /api/v1/chats:
    get:
      tags:
        - Chat
      operationId: getChats
      summary: Получить список чатов пользователя
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Авторизационный токен.

        - in: query
          name: skip
          schema:
            type: integer
          required: false
          description: Количество пропускаемых записей (параметр пагинации)

        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: Количество взятых записей (параметр пагинации)

      responses:
        '200':
          description: Список чатов
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Chats'
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      tags:
        - Chat
      operationId: createChat
      summary: Создать чат
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Авторизационный токен.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatCreate'

      responses:
        '201':
          description: Чат создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/chats/{chatId}:
    get:
      tags:
        - Chat
      operationId: getChat
      summary: Получить информацию о чате
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Авторизационный токен.

        - in: path
          name: chatId
          required: true
          schema:
            type: string
          description: Идентификатор чата

      responses:
        '200':
          description: Информация о чате
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatInfo'
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Доступ запрещен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '404':
          description: Чат не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - Chat
      operationId: leveChat
      summary: Покинуть чат
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Авторизационный токен.

        - in: path
          name: chatId
          required: true
          schema:
            type: string
          description: Идентификатор чата

      responses:
        '204':
          description: Пользователь вышел из чата

        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Доступ запрещен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '404':
          description: Чат не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/chats/{chatId}/name:
    patch:
      tags:
        - Chat
      operationId: updateChat
      summary: Изменить название чата
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Авторизационный токен.

        - in: path
          name: chatId
          required: true
          schema:
            type: string
          description: Идентификатор чата

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Новое название чата
              required:
                - name

      responses:
        '200':
          description: Информация о чате обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Доступ запрещен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '404':
          description: Чат не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
  /api/v1/chats/{chatId}/users:
    post:
      tags:
        - Chat
      operationId: addUserToChat
      summary: Добавить пользователя в чат
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Авторизационный токен.

        - in: path
          name: chatId
          required: true
          schema:
            type: string
          description: Идентификатор чата

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: Идентификатор пользователя
                  example: "5f7b1b7b7f7b1b7b7f7b1b7b"

      responses:
        '201':
          description: Пользователь добавлен в чат
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatUser'

        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Доступ запрещен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '404':
          description: Чат не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/chats/{chatId}/messages:
    get:
      tags:
        - Chat
      operationId: getMessages
      summary: Получить список сообщений чата
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Авторизационный токен.

        - in: path
          name: chatId
          required: true
          schema:
            type: string
          description: Идентификатор чата

        - in: query
          name: skip
          schema:
            type: integer
          required: false
          description: Количество пропускаемых записей (параметр пагинации)

        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: Количество взятых записей (параметр пагинации)

      responses:
        '200':
          description: Список сообщений
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Messages'
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Доступ запрещен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '404':
          description: Чат не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/chats/{chatId}/messages/{messageId}/thread:
    get:
      tags:
        - Chat
      operationId: getThread
      summary: Получить тред
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Авторизационный токен.

        - in: path
          name: chatId
          required: true
          schema:
            type: string
          description: Идентификатор чата

        - in: path
          name: messageId
          required: true
          schema:
            type: string
          description: Идентификатор сообщения

        - in: query
          name: skip
          schema:
            type: integer
          required: false
          description: Количество пропускаемых записей (параметр пагинации)

        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: Количество взятых записей (параметр пагинации)

      responses:
        '200':
          description: Ветка сообщений
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Thread'
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Доступ запрещен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '404':
          description: Тред не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    Chats:
      $ref: "../Dto/Chats/chats.schema.json"
    ChatCreate:
      $ref: "../Dto/Chats/chat-create.schema.json"
    Chat:
      $ref: "../Dto/Chats/chat.schema.json"
    ChatUser:
      $ref: "../Dto/Chats/chat-user.schema.json"
    ChatInfo:
      $ref: "../Dto/Chats/chat-info.schema.json"
    Message:
      $ref: "../Dto/Messages/message.schema.json"
    Messages:
      $ref: "../Dto/Messages/messages.schema.json"
    Thread:
      $ref: "../Dto/Threads/thread.schema.json"
    Error:
      $ref: "../Dto/Common/error.schema.json"